### ISSUE TITLE
'external' glitch

### ISSUE THREAD

**Issue by divipp** [cobbpg/elerea#10]
In a multithreaded environment use of `external` can cause a glitch.

The following program returns `False` instead of `True`:

    -- slowFib is used to force a specific unlucky scheduling
    slowFib 0 = 0
    slowFib 1 = 1
    slowFib n = slowFib (n-1) + slowFib (n-2)

    externalGlitch = do
        (sig, snk) <- external 0
        forkIO $ slowFib 20 `seq` snk 1
        join $ start $ return $ liftM2 (==) sig (slowFib 22 `seq` sig)

I guess this is a bug.

**Comment by cobbpg** [comment]
Yes, this should be treated as a bug!

**Comment by cobbpg** [comment]
Solved in 2.9.0 with the introduction of managed external signals.
