### ISSUE TITLE
Add to stackage? 

### ISSUE THREAD

**Issue by dmjio** [cobbpg/elerea#15]
Happily using elerea for some projects, would be nice if it could be added to LTS stackage. https://www.stackage.org/

**Comment by cobbpg** [comment]
Yes, that could be done. I'm actually planning to release a new version soon in response to some semantic issues, so I can try to sort out stackage distribution at the same time.

**Comment by cobbpg** [comment]
Submitted.

**Comment by dmjio** [comment]
Thank you!
