### ISSUE TITLE
'snapshot' glitch

### ISSUE THREAD

**Issue by divipp** [cobbpg/elerea#9]
For me the behaviour of `snapshot` is counterintuitive (and makes a bit harder to model elerea in another FRP library).

In the pure model, `snapshot` is the identity function.
However, it can change the order of IO effects:

    example n = do
        smp <- start $ do
            s <- effectful $ print "?"
            replicateM_ n $ snapshot s
            return s
        print "!"
        smp

Sample outputs:

    example 0    -->   !?
    example 1    -->   ?!
    example 2    -->   ?!

I guess the current behaviour is the intended behaviour.
From my point of view it would be more consistent to get always "?!", kind of pre-cache all signal values when running the `SignalGen` monad.
This way I think the order of side-effects would be more predictable. Also this is needed to make the Signal monad commutative:

    m1 :: Signal a
    m2 :: Signal b
    liftA2 (,) m1 m2   ~~  swap <$> (liftA2 (,) m2 m1)

**Comment by cobbpg** [comment]
Yes, the pure model doesn’t apply when `effectful` is involved. Things get complicated because Elerea with effectful signals is essentially a cooperative multitasking system, and the order of execution is undefined by design. I don’t think imposing a total ordering would be a good idea, but it might be interesting to provide some means to define a partial order when more control is needed. In fact, this would be very similar to how scripts are coordinated in Unity3D.

In any case, `effectful` is there to make it easier to interface with imperative libraries that perform some form of number crunching that’s technically not a side-effect. I introduced it for the sake of Bullet, where the order of these invocations shouldn’t matter as long as we don’t step the world. It’s morally dubious to use it for anything else, but sadly there’s no practical way to constrain it on the application side I can think of.

**Comment by divipp** [comment]
Thanks for the clarification about the usage of `effectful`.
As a side note, according to the documentation, `effectful` is for library writers, however the dow example also uses it.

But the problem seems to be related to `snapshot`.
I can reproduce the strange behaviour without `effectful`:

    strange n = do
        (sig, snk) <- external "0"
        smp <- start $ do
            v <- generator $ pure $ snapshot sig
            replicateM_ n $ snapshot v
            return $ liftM2 (++) v sig
        snk "2"
        v1 <- smp
        print v1

Sample outputs:

    strange 0     -->    "22"
    strange 1     -->    "02"
    strange 2     -->    "02"

**Comment by divipp** [comment]
One solution is to do the first sampling in `start`, and the first invocation of the result action would do nothing but give back the already sampled value. This seems to be a hack though.

**Comment by divipp** [comment]
Another example shows that with the help of the misbehaviour one can distinguish `memo` from `return`:

    testMemo memoFun = do
        (sig, snk) <- external "memo"
        smp <- start $ mdo
            s' <- delay "" s
            s <- memoFun $ liftA2 (++) sig s'
            snapshot s
            return s
        snk "return"
        smp

Outputs:

    testMemo memo     -->   "memo"
    testMemo return     -->   "return"

**Comment by cobbpg** [comment]
Yes, it definitely shouldn’t be possible to produce inconsistent behaviour without invoking `effectful`.

**Comment by divipp** [comment]
Btw with the same trick one can test whether `snapshot` was called on a signal, which of course should not be possible:

    testSnapshot f = do
        (sig, snk) <- external "snapshot was called"
        smp <- start $ mdo
            s' <- delay "" s
            s <- memo $ liftA2 (++) sig s'
            f s
            return s
        snk "snapshot was not called"
        smp

Outputs:

    testSnapshot (\s -> return ())    -->    "snapshot was not called"
    testSnapshot snapshot    -->    "snapshot was called"

**Comment by divipp** [comment]
Ok, I think so far this is the clearest presentation of the bug:

    -- according to the pure semantics, copy === return
    copy :: Signal a -> SignalGen (Signal a)
    copy s = do
        c <- generator . return . snapshot $ s
        snapshot c
        return c

    -- returns False instead of True
    glitch :: IO Bool
    glitch = do
        (sig, snk) <- external 0
        smp <- start $ do
            sig' <- copy sig
            return $ liftA2 (==) sig' sig
        snk 1
        smp

**Comment by cobbpg** [comment]
Coming to think of it, making `external` a managed signal like you proposed in #13 would solve all these issues. Essentially `snapshot` behaves a bit like `seq`, so if the external signal was pre-sampled at the beginning, laziness couldn't reach across the superstep boundary.

**Comment by cobbpg** [comment]
The new 2.9.0 version introduces managed external signals that prevent all the weird glitches listed above.
